# -*- coding: utf-8 -*-
"""first-functional-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srdeW4lIaopLUnK_lyLN4F-HegEnLnao
"""

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

from keras.layers import*

# now we will give input to our neural network and for that we use Input layer and tell the shape of our input to the neural network and stored it in one varaiable

from tensorflow.keras.layers import Input

x = Input(shape=(3,))

# Make further layers
# 2 dense layers-> you have to given a name to every layer hideen1 and ab yeh bhi btana padega ya hidden layer kiss se connected hai or ki hidden layer ko input kha se mil rha hai


hidden1=Dense(128,activation='relu')(x)
hidden2=Dense(64,activation='relu')(hidden1)

# now we will do branching in branch 1 age prediction and in branch 2 place prediction
# prediction 1 : age: linear activation function beacuse It is a regression problem
#prediction 2 : city: sigmoid : classification problem hai


output1=Dense(1, activation='linear')(hidden2)
output2=Dense(1, activation='sigmoid')(hidden2)

model = Model(inputs=x, outputs=[output1, output2])

model.summary()

from keras.utils import plot_model
plot_model(model,show_shapes=True)